menu:
  # Home: /
  # Archives: archives
  page:
    Archives: archives
    Project: project
    About: about

widgets:
- tag
# - search
# - blogroll

excerpt_link: Continue →

mathjax: true
fancybox: true
print: false

social:
  twitter: false
  github: true
  weibo: true
  gplus: false
  rss: false

twitter:
  username:

github:
  username: ielgnaw

weibo:
  username: justjava

gplus:
  username:

addthis: #SNS分享，身在天朝，当然用“百度分享”，暂时默认，后面会介绍
  enable: false
  pubid:
  # facebook: false
  twitter: false
  google: false
  pinterest: false
